//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.08 at 01:46:11 PM GMT+03:00 
//


package kte.labs.task.soap.clients;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for client complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="client"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="individualDiscount1" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="individualDiscount2" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "client", propOrder = {
    "id",
    "name",
    "individualDiscount1",
    "individualDiscount2"
})
public class Client {

    protected long id;
    @XmlElement(required = true)
    protected String name;
    protected int individualDiscount1;
    protected int individualDiscount2;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the individualDiscount1 property.
     * 
     */
    public int getIndividualDiscount1() {
        return individualDiscount1;
    }

    /**
     * Sets the value of the individualDiscount1 property.
     * 
     */
    public void setIndividualDiscount1(int value) {
        this.individualDiscount1 = value;
    }

    /**
     * Gets the value of the individualDiscount2 property.
     * 
     */
    public int getIndividualDiscount2() {
        return individualDiscount2;
    }

    /**
     * Sets the value of the individualDiscount2 property.
     * 
     */
    public void setIndividualDiscount2(int value) {
        this.individualDiscount2 = value;
    }

}
