//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.08 at 01:46:11 PM GMT+03:00 
//


package kte.labs.task.soap.clients;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.user.spring.ws.clients package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.user.spring.ws.clients
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetClientByIdRequest }
     * 
     */
    public GetClientByIdRequest createGetClientByIdRequest() {
        return new GetClientByIdRequest();
    }

    /**
     * Create an instance of {@link GetClientByIdResponse }
     * 
     */
    public GetClientByIdResponse createGetClientByIdResponse() {
        return new GetClientByIdResponse();
    }

    /**
     * Create an instance of {@link Client }
     * 
     */
    public Client createClient() {
        return new Client();
    }

    /**
     * Create an instance of {@link GetAllClientsRequest }
     * 
     */
    public GetAllClientsRequest createGetAllClientsRequest() {
        return new GetAllClientsRequest();
    }

    /**
     * Create an instance of {@link GetAllClientsResponse }
     * 
     */
    public GetAllClientsResponse createGetAllClientsResponse() {
        return new GetAllClientsResponse();
    }

}
